#!/bin/bash
# ----------------------------------------------------------------
# -- This profile script sets virtualenv settings.              --
# --                                                            --
# -- The contents of a this script are generated by Chef.       --
# -- Do not change them unless you are *sure* you know what     --
# -- you're doing.                                              --
# ----------------------------------------------------------------

# Include virtualenvwrapper.
. <%= node['python']['virtualenv']['wrapper']['filename'] %>

# Ensure that virtualenvs are created in a consistent location.
export WORKON_HOME=<%= node['python']['virtualenv']['path'] %>
